version: '3'
services:
  app:
    image: 'steam-frontend'
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
    - 80:80
    - 443:443
    networks:
    - steam-friends-fastify_backend
networks:
  steam-friends-fastify_backend:
    external: true